export const wordPairs = [
  // FOOD & DRINKS
  { common: "Pizza", odd: "Burger" },
  { common: "Tea", odd: "Coffee" },
  { common: "Apple", odd: "Orange" },
  { common: "Bread", odd: "Toast" },
  { common: "Ice Cream", odd: "Frozen Yogurt" },
  { common: "Cake", odd: "Cupcake" },
  { common: "Spaghetti", odd: "Noodles" },
  { common: "Sandwich", odd: "Wrap" },
  { common: "Milk", odd: "Cream" },
  { common: "Cookie", odd: "Biscuit" },
  { common: "Cheese", odd: "Butter" },
  { common: "Soup", odd: "Stew" },
  { common: "Salad", odd: "Coleslaw" },
  { common: "Pancake", odd: "Waffle" },
  { common: "Juice", odd: "Smoothie" },

  // HOME & APPLIANCES
  { common: "Refrigerator", odd: "Air Conditioner" },
  { common: "Sofa", odd: "Chair" },
  { common: "Bed", odd: "Couch" },
  { common: "Table", odd: "Desk" },
  { common: "Television", odd: "Monitor" },
  { common: "Lamp", odd: "Flashlight" },
  { common: "Oven", odd: "Microwave" },
  { common: "Washing Machine", odd: "Dishwasher" },
  { common: "Fan", odd: "Heater" },
  { common: "Mirror", odd: "Window" },
  { common: "Curtain", odd: "Blinds" },
  { common: "Carpet", odd: "Rug" },
  { common: "Pillow", odd: "Cushion" },
  { common: "Blanket", odd: "Sheet" },
  { common: "Clock", odd: "Watch" },

  // TRANSPORTATION
  { common: "Car", odd: "Motorcycle" },
  { common: "Bus", odd: "Train" },
  { common: "Airplane", odd: "Helicopter" },
  { common: "Bicycle", odd: "Scooter" },
  { common: "Boat", odd: "Ship" },
  { common: "Taxi", odd: "Uber" },
  { common: "Truck", odd: "Van" },
  { common: "Metro", odd: "Subway" },
  { common: "Rocket", odd: "Spaceship" },
  { common: "Skateboard", odd: "Roller Skates" },

  // ANIMALS
  { common: "Dog", odd: "Wolf" },
  { common: "Cat", odd: "Tiger" },
  { common: "Horse", odd: "Zebra" },
  { common: "Cow", odd: "Bull" },
  { common: "Chicken", odd: "Duck" },
  { common: "Lion", odd: "Leopard" },
  { common: "Elephant", odd: "Rhino" },
  { common: "Monkey", odd: "Ape" },
  { common: "Fish", odd: "Shark" },
  { common: "Bird", odd: "Bat" },
  { common: "Rabbit", odd: "Hamster" },
  { common: "Bear", odd: "Panda" },
  { common: "Deer", odd: "Moose" },
  { common: "Fox", odd: "Raccoon" },
  { common: "Dolphin", odd: "Whale" },

  // TOOLS & OBJECTS
  { common: "Knife", odd: "Scissors" },
  { common: "Hammer", odd: "Screwdriver" },
  { common: "Pen", odd: "Pencil" },
  { common: "Book", odd: "Magazine" },
  { common: "Phone", odd: "Tablet" },
  { common: "Computer", odd: "Laptop" },
  { common: "Key", odd: "Lock" },
  { common: "Spoon", odd: "Fork" },
  { common: "Plate", odd: "Bowl" },
  { common: "Cup", odd: "Mug" },
  { common: "Brush", odd: "Comb" },
  { common: "Towel", odd: "Napkin" },
  { common: "Bag", odd: "Backpack" },
  { common: "Umbrella", odd: "Raincoat" },
  { common: "Glasses", odd: "Sunglasses" },

  // NATURE & PLACES
  { common: "Ocean", odd: "Lake" },
  { common: "Mountain", odd: "Hill" },
  { common: "Forest", odd: "Jungle" },
  { common: "Desert", odd: "Beach" },
  { common: "River", odd: "Stream" },
  { common: "Garden", odd: "Park" },
  { common: "City", odd: "Town" },
  { common: "Island", odd: "Peninsula" },
  { common: "Valley", odd: "Canyon" },
  { common: "Cave", odd: "Tunnel" },

  // WEATHER & SEASONS
  { common: "Rain", odd: "Snow" },
  { common: "Sun", odd: "Moon" },
  { common: "Wind", odd: "Breeze" },
  { common: "Storm", odd: "Thunder" },
  { common: "Summer", odd: "Winter" },
  { common: "Spring", odd: "Autumn" },
  { common: "Hot", odd: "Warm" },
  { common: "Cold", odd: "Cool" },
  { common: "Cloud", odd: "Fog" },
  { common: "Lightning", odd: "Flash" },

  // SPORTS & ACTIVITIES
  { common: "Football", odd: "Soccer" },
  { common: "Basketball", odd: "Volleyball" },
  { common: "Tennis", odd: "Badminton" },
  { common: "Swimming", odd: "Diving" },
  { common: "Running", odd: "Jogging" },
  { common: "Dancing", odd: "Singing" },
  { common: "Reading", odd: "Writing" },
  { common: "Cooking", odd: "Baking" },
  { common: "Painting", odd: "Drawing" },
  { common: "Golf", odd: "Mini Golf" },

  // COLORS & SHAPES
  { common: "Red", odd: "Pink" },
  { common: "Blue", odd: "Purple" },
  { common: "Green", odd: "Lime" },
  { common: "Yellow", odd: "Orange" },
  { common: "Black", odd: "Gray" },
  { common: "Circle", odd: "Oval" },
  { common: "Square", odd: "Rectangle" },
  { common: "Triangle", odd: "Diamond" },

  // BODY & HEALTH
  { common: "Doctor", odd: "Nurse" },
  { common: "Medicine", odd: "Vitamin" },
  { common: "Hospital", odd: "Clinic" },
  { common: "Dentist", odd: "Orthodontist" },
  { common: "Exercise", odd: "Workout" },
  { common: "Head", odd: "Face" },
  { common: "Hand", odd: "Finger" },
  { common: "Foot", odd: "Toe" },

  // ENTERTAINMENT
  { common: "Movie", odd: "Documentary" },
  { common: "Music", odd: "Song" },
  { common: "Game", odd: "Puzzle" },
  { common: "Comedy", odd: "Drama" },
  { common: "Theater", odd: "Cinema" },
  { common: "Concert", odd: "Festival" },
  { common: "Party", odd: "Celebration" },
  { common: "Vacation", odd: "Holiday" }
];
